### ISSUE TITLE
Redirect to initialize page if refresh token is invalid

### ISSUE THREAD

**Issue by jlyon** [GovReady/GovReady-Drupal-Agent#48]
Currently there is a "Problem contacting..." error displayed.

If the call to /sites/:siteId returns a 403, we should force the user to re-login and "initialize" the govready_options variable.

**Comment by gregelin** [comment]
@jlyon How goes this issue?

**Comment by aschmoe** [comment]
@gregelin Fixed up this issue and pushed up to the server, should be looking good!

**Comment by gregelin** [comment]
Great!

**Comment by aschmoe** [comment]
@gregelin since Jeff alerted me to an issue with the easy fix I tried to implement...

- drupal 7 + 8 branches are updated on github and drupal.org
- wordpress branches are updated on github
- http://drupal.plugin.govready.com/ is updated
- http://wordpress.plugin.govready.com/ is updated
- http://live-freedonia-dkan.pantheonsite.io/ is updated
- https://plugin.govready.com is updated

**Comment by aschmoe** [comment]
Also any code pulling the client branch (like govready Q) will also be updated
